# Generated by Django 2.1 on 2019-11-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_product_in_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_change_deliver', 'Может менять доставку'), ('can_cancel', 'Может отменять заказ')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
